manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: infely
      url-base: https://github.com/infely
  projects:
    # - name: zmk
    #  remote: zmkfirmware
    #  revision: main
    #  import: app/west.yml
    - name: zmk
      remote: badjeff
      revision: feat/pointers-with-input-processors
      import: app/west.yml
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-output-relay
      remote: badjeff
      revision: main
    - name: cirque-input-module
      remote: badjeff
      revision: main
    - name: nice-view-battery
      remote: infely
      revision: main
  self:
    path: config
