manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: infely
      url-base: https://github.com/infely
    - name: FuzzyFuzzio
      url-base: https://github.com/FuzzyFuzzio
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-battery
      remote: FuzzyFuzzio
      revision: main
    - name: zmk-split-layer-sync
      remote: FuzzyFuzzio
      revision: main
  self:
    path: config
